var americasDataArray  = [
  {content: 'U.S. independence', start: '1776-07-04'},
  {content: 'Settlers arrive', start: '1607-09-01'},
  {content: 'Columbus',   start: '1492-09-01'},
  {content: 'Cueva de las Manos', start: '-009000-03-15',
   title: '<img height="275px" src="img/CuevaManos.jpg" alt=""><br>Cueva de las Manos, located in<br>Perito Moreno, Argentina', 
   image: '<img height="225px" src="img/CuevaManos.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: 'Vis.js comes with a flexible DataSet, which can be'},
  {content: 'Toquepala', start: '-009500-03-15',
   title: '<img height="275px" src="img/Toquepala.JPG" alt=""><br>Toquepala Caves<br>located in southeast Peru', 
   image: '<img height="225px" src="img/Toquepala.JPG" alt="">',
   imageOther: '<img src="" alt="">',
   description: 'Vis.js comes with a flexible DataSet, which can be'},
  {content: 'Folsom Point', start: '-008750-03-15',
   title: '<img src="img/Folsom_point.jpg" alt=""><br>Folsom Point',
   image: '<img src="img/Folsom_point.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: 'Vis.js comes with a flexible DataSet, which can be'},
  {content: 'Clovis Point', start: '-011500-03-15',
   title: '<img src="img/Clovis_Point.jpg" alt=""><br>Clovis projectile point', 
   image: '<img src="img/Clovis_Point.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: 'Vis.js comes with a flexible DataSet, which can be'},
  {content: 'Tikal', start: '0400-03-15',
   title: '<img height="275px" src="img/Tikal.jpg" alt=""><br>ancient Myan citadel', 
   image: '<img height="225px" src="img/Tikal.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: 'Vis.js comes with a flexible DataSet, which can be'}
];

