var europeDataArray  = [
  {content: 'WWII',       start: '1939-09-01',
   title: '<img src="" alt="">',
   image: '<img src="" alt="">',
   imageOther: '<img src="" alt="">',
   description: ''},
  {content: 'Mona Lisa',  start: '1505-06-01',
   title: '<img src="" alt="">',
   image: '<img src="" alt="">',
   imageOther: '<img src="" alt="">',
   description: ''},
  {content: 'Plato',      start: '-000380-04-25',
   title: '<img height="300px" src="img/Plato.jpg" alt=""><br>Plato',
   image: '<img height="500px" src="img/Plato.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: 'Plato was a philosopher in Classical Greece and the founder of the Academy in Athens, the first institution of higher learning in the Western world. He is widely considered the most pivotal figure in the development of philosophy, especially the Western tradition. Unlike nearly all of his philosophical contemporaries, Plato\'s entire work is believed to have survived intact for over 2,400 years. Others believe that the oldest extant manuscript dates to around AD 895, 1100 years after Plato\'s death. This makes it difficult to know exactly what Plato wrote. Along with his teacher, Socrates, and his most famous student, Aristotle, Plato laid the very foundations of Western philosophy and science.<br><li>470-399 Socrates</li><li>428-348 Plato</li><li>384-322 Aristotle</li>'},
  {content: 'Rome Fell',  start: '0476-09-01', //original: img/RomulusAugustus.jpg
    title: '<img height="300px" src="img/Romulus_resigns_the_crown.jpg" alt=""><br>Romulus Augustulus,<br>overthrown by Germania',
    image: '<img height="" src="img/Romulus_resigns_the_crown.jpg" alt=""><br>Romulus Augustulus resigns his crown to Odoacer.<br>1880 illustration',
   imageOther: '<img src="" alt="">',
    description: '<p>In 476, Orestes refused to grant Odoacer and the Heruli federated status, prompting an invasion. Orestes fled to the city of Pavia on August 23, 476, where the city\'s bishop gave him sanctuary. Orestes was soon forced to flee Pavia when Odoacer\'s army broke through the city walls, and his army ravaged the city. Odoacer\'s army chased Orestes to Piacenza, where they captured and executed him on August 28, 476.</p><p>On September 4, 476, Odoacer forced then 16-year-old Romulus Augustulus, whom his father Orestes had proclaimed to be Rome\'s Emperor, to abdicate. After deposing Romulus, Odoacer did not execute him. The Anonymus Valesianus wrote that Odoacer, "taking pity on his youth", spared Romulus\' life and granted him an annual pension of 6,000 solidi before sending him to live with relatives in Campania. Odoacer then installed himself as ruler over Italy, and sent the Imperial insignia to Constantinople.</p>'},
  {content: 'Pantheon',   start: '0123-09-01',
   title: '<img height="225px" src="img/Pantheon.jpg" alt=""><br>Temple in Rome, Italy', 
   image: '<img height="500px" src="img/Pantheon.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: 'Vis.js comes with a flexible DataSet, which can be'},
  {content: 'Parthenon', start: '-000439-06-01',
   title: '<img height="275px" src="img/Parthenon.jpg" alt=""><br>Temple in Athens, Greece',
   image: '<img height="500px" src="img/Parthenon.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: ''},
  {content: 'Rome founded', start: '-000753-09-01',
   title: '<img src="" alt="">',
   image: '<img src="" alt="">',
   imageOther: '<img src="" alt="">',
   description: ''},
  {content: 'Crusades',  start: '1191-09-07',
   title: '<img height="325px" src="img/Crusades.jpg" alt=""><br>Battle of Arsuf',
   image: '<img height="250px" src="img/Crusades.jpg" alt=""><br>Battle of Arsuf<br>by Dore 1871',
   imageOther: '<img src="" alt="">',
   description: ""},
  {content: 'Napoleon',   start: '1809-05-18',
   title: '<img src="" alt="">',
   image: '<img src="" alt="">',
   imageOther: '<img src="" alt="">',
   description: ''},
  {content: 'Stonehedge', start: '-003100-05-18',
   title: '<img height="275px" src="img/Stonehenge.jpg" alt=""><br>Prehistoric monument in England',
   image: '<img height="400px" src="img/Stonehenge.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: 'Stonehenge is a prehistoric monument in Wiltshire, England, 2 miles (3 km) west of Amesbury and 8 miles (13 km) north of Salisbury. It consists of a ring of standing stones, with each standing stone around 13 ft (4.1 metres) high, 6 ft 11 in (2.1 metres) wide and weighing around 25 tons. The stones are set within earthworks in the middle of the most dense complex of Neolithic and Bronze Age monuments in England, including several hundred burial mounds. Archaeologists believe it was constructed from 3000 BC to 2000 BC. The surrounding circular earth bank and ditch, which constitute the earliest phase of the monument, have been dated to about 3100 BC. Radiocarbon dating suggests that the first bluestones were raised between 2400 and 2200 BC, although they may have been at the site as early as 3000 BC.'},
  {content: 'Decorative Jug', start: '-001537-05-18', 
   title: '<img height="300px" src="img/Minoan_Decorated_Jug.jpg" alt=""><br>Minoan decorative jug',
   image: '<img height="450px" src="img/Minoan_Decorated_Jug.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: ""},
  {content: 'Knossos',    start: '-001900-05-18',
   title: '<img height="275px" src="img/Knossos.jpg" alt=""><br>Ceremonial and political centre of the Minoan civilization',
   image: '<img height="450px" src="img/Knossos.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: ""},
  {content: 'Alexander the Great', start: '-000336-05-18',
   title: '<img height="275px" src="img/Alexander_the_Great.jpg" alt=""><br>Alexander the Great',
   image: '<img height="450px" src="img/Alexander_the_Great.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: 'King of the Ancient Greek kingdom of Macedon, he had created one of the largest empires of the ancient world by the age of thirty, stretching from Greece to northwestern India.'},
  {content: 'Julius Caesar', start: '-000044-03-15',
   title: '<img height="250px" src="img/La_morte_di_Cesare.jpg" alt=""><br>Death of Julius Caesar',
   image: '<img height="450px" src="img/La_morte_di_Cesare.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: ""},
  {content: 'Venus Figurines', start: '-026500-03-15',
   title: '<img src="img/Venus_of_Willendorf.jpg" alt=""><br>Venus of Willendorf',
   image: '<img src="img/Venus_of_Willendorf.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: ""},
  {content: 'Barnenez', start: '-004800-03-15',
   title: '<img height="275px" src="img/Barnenez.jpg" alt=""><br>Cairn of Barnenez, located in France',
   image: '<img height="450px" src="img/Barnenez.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: ""},
  {content: 'Chauvet Cave', start: '-026500-03-15',
   title: '<img height="325px" src="img/Chauvet.jpg" alt=""><br>Replica of painting in Chauvet Cave',
   image: '<img height="450px" src="img/Chauvet.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: ""},
  {content: 'Venus de Brassempouy', start: '-023000-03-15',
   title: '<img src="img/Venus_de_Brassempouy.jpg" alt=""><br>Venus de Brassempouy<br>discovered in 1892 France',
   image: '<img src="img/Venus_de_Brassempouy.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: ""},
  {content: 'Azilian points', start: '-008000-06-15',
   title: '<img height="300px" src="img/Azilian_points.jpg" alt=""><br>Azilian points(1.8x0.5x0.3in),<br>microliths from France and Spain',
   image: '<img height="450px" src="img/Azilian_points.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: ""}
];





