var middleEastDataArray  = [
  {group: 3, content: 'Aleppo',    start: '-005000-06-01',
   title: '<img height="275px" src="img/Aleppo.jpg" alt=""><br>Ancient city in Syria,<br>a settlement in 5000BC<br>', 
   image: '<img height="500px" src="img/Aleppo.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: 'Vis.js comes with a flexible DataSet, which can be'},
  {group: 3, content: 'Cuneiform', start: '-003200-09-01',
   title: '<img height="275px" src="img/Cuneiform.jpg" alt=""><br>Early system of writing', 
   image: '<img height="500px" src="img/Cuneiform.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: 'Vis.js comes with a flexible DataSet, which can be'},
  {group: 3, content: 'Ishtar Gate', start: '-000575-05-18',
   title: '<img height="275px" src="img/Ishtar_Gate.jpg" alt=""><br>Built in Babylon, modern day Iraq', 
   image: '<img height="500px" src="img/Ishtar_Gate.jpg" alt="">',
   imageOther: '<img height="300px" src="img/Ishtar_in_Iraq.jpg" alt="">',
   description: 'The Ishtar Gate was the eighth gate to the inner city of Babylon. It was constructed in about 575 BCE by order of King Nebuchadnezzar II on the north side of the city. It was excavated in the early 20th century and a reconstruction using original bricks is now shown in the Pergamon Museum, Berlin.'},
  {group: 3, content: 'Wheel', start: '-003500-03-15',
   title: '<img height="300px" src="img/wheel.jpg" alt=""><br>Pottery wheel invented<br>Used on chariots 300 years later', 
   image: '<img height="500px" src="img/wheel.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: 'Vis.js comes with a flexible DataSet, which can be'},
  {group: 3, content: 'Statue of Gudea', start: '-002090-03-15',
   title: '<img height="325px" src="img/Statue_of_Gudea.jpg" alt=""><br>Statue of Gudea,<br>Gudea ruled between 2144-2124 BC', 
   image: '<img height="550px" src="img/Statue_of_Gudea.jpg" alt="">',
   imageOther: '<img height="350px" src="img/Mesopotamia_map.jpg" alt="">',
   description: 'Approximately twenty-seven statues of Gudea, a ruler (ensi) of the state of Lagash have been found in southern Mesopotamia. Gudea ruled between ca. 2144 - 2124 BC and the statues demonstrate a very sophisticated level of craftsmanship for the time. The known statues have been categorised \'A-AA\' by archaeologists.'}
];

