var middleEastDataArray  = [
  {content: 'Aleppo',    start: '-005000-06-01',
   title: '<img height="275px" src="img/Aleppo.jpg" alt=""><br>Ancient city in Syria,<br>a settlement in 5000BC<br>', 
   image: '<img height="500px" src="img/Aleppo.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: '<p>Aleppo is a city in Syria, serving as the capital of the Aleppo Governorate, the most populous Syrian governorate. With an official population of 4.6 million in 2010, Aleppo was the largest Syrian city before the Syrian Civil War; however, now Aleppo is likely the second-largest city in Syria after the capital Damascus.</p><p>Aleppo is an ancient city, and one of the oldest continuously inhabited cities in the world; it may have been inhabited since the 6th millennium BC. Excavations at Tell as-Sawda and Tell al-Ansari, just south of the old city of Aleppo, show that the area was occupied by Amorites since at least the latter part of the 3rd millennium BC. This is also when Aleppo is first mentioned in cuneiform tablets unearthed in Ebla and Mesopotamia, in which it is a part of the Amorite state of Yamhad, and is noted for its commercial and military proficiency. Such a long history is attributed to its strategic location as a trading center midway between the Mediterranean Sea and Mesopotamia (i.e. modern Iraq).</p>'},
  {content: 'Cuneiform', start: '-003200-09-01',
   title: '<img height="275px" src="img/Cuneiform.jpg" alt=""><br>Early system of writing', 
   image: '<img height="500px" src="img/Cuneiform.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: '<p>Cuneiform script, one of the earliest systems of writing, was invented by the Sumerians. It is distinguished by its wedge-shaped marks on clay tablets, made by means of a blunt reed for a stylus. The name cuneiform itself simply means "wedge shaped".</p><p>Emerging in Sumer in the late fourth millennium BC to convey the Sumerian language which was a language isolate (the Uruk IV period), cuneiform writing began as a system of pictograms. In the third millennium, the pictorial representations became simplified and more abstract as the number of characters in use grew smaller (Hittite cuneiform). The system consists of a combination of logophonetic, consonantal alphabetic and syllabic signs.</p>'},
  {content: 'Ishtar Gate', start: '-000575-05-18',
   title: '<img height="275px" src="img/Ishtar_Gate.jpg" alt=""><br>Built in Babylon, modern day Iraq', 
   image: '<img height="500px" src="img/Ishtar_Gate.jpg" alt="">',
   imageOther: '<img height="300px" src="img/Ishtar_in_Iraq.jpg" alt="">',
   description: 'The Ishtar Gate was the eighth gate to the inner city of Babylon. It was constructed in about 575 BCE by order of King Nebuchadnezzar II on the north side of the city. It was excavated in the early 20th century and a reconstruction using original bricks is now shown in the Pergamon Museum, Berlin.'},
  {content: 'Wheel', start: '-003500-03-15',
   title: '<img height="300px" src="img/wheel.jpg" alt=""><br>Pottery wheel invented<br>Used on chariots 300 years later', 
   image: '<img height="500px" src="img/wheel.jpg" alt="">',
   imageOther: '<img src="" alt="">',
   description: '<p>The invention of the wheel falls into the late Neolithic, and may be seen in conjunction with other technological advances that gave rise to the early Bronze Age. Note that this implies the passage of several wheel-less millennia even after the invention of agriculture and of pottery, during the Aceramic Neolithic (9500-6500 BCE).</p><p>Precursors of wheels, known as "tournettes" or "slow wheels", were known in the Middle East by the 5th millennium BCE (one of the earliest examples was discovered at Tepe Pardis, Iran, and dated to 5200-4700 BCE). These were made of stone or clay and secured to the ground with a peg in the center, but required effort to turn. True (freely-spinning) potter\'s wheels were apparently in use in Mesopotamia by 3500 BCE and possibly as early as 4000 BCE, and the oldest surviving example, which was found in Ur (modern day Iraq), dates to approximately 3100 BCE.</p>'},
  {content: 'Statue of Gudea', start: '-002090-03-15',
   title: '<img height="325px" src="img/Statue_of_Gudea.jpg" alt=""><br>Statue of Gudea,<br>Gudea ruled between 2144-2124 BC', 
   image: '<img height="550px" src="img/Statue_of_Gudea.jpg" alt="">',
   imageOther: '<img height="350px" src="img/Mesopotamia_map.jpg" alt="">',
   description: 'Approximately twenty-seven statues of Gudea, a ruler (ensi) of the state of Lagash have been found in southern Mesopotamia. Gudea ruled between ca. 2144 - 2124 BC and the statues demonstrate a very sophisticated level of craftsmanship for the time. The known statues have been categorised \'A-AA\' by archaeologists.'}
];

